export const TOGGLE_EDITING = "TOGGLE_EDITING";
export const EDIT_FIRST_NAME = "EDIT_FIRST_NAME";
export const EDIT_LAST_NAME = "EDIT_LAST_NAME";
export const EDIT_EMAIL_ADDRESS = "EDIT_EMAIL_ADDRESS";
export const EDIT_BIRTHDAY = "EDIT_BIRTHDAY";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const EDIT_FULLNAME = "EDIT_FULLNAME";
